<?php
session_start();

$routerHost = '192.168.0.1:8443';
$verifyTls = false;
$timeoutSec = 10;
$sampleDelayUs = 1000000;
$routerUser = (string)($_SESSION['router_user'] ?? '');
$routerPass = (string)($_SESSION['router_pass'] ?? '');
if ($routerUser === '' || $routerPass === '') { header('Location: index.php'); exit; }

function h(?string $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function formatBitsPerSecond(float $b, int $p=2): string { $u=['bps','Kbps','Mbps','Gbps','Tbps'];$b=max(0,$b);$n=$b>0?floor(log($b,1000)):0;$n=min($n,count($u)-1);return round($b/(1000**$n),$p).' '.$u[$n]; }
function routerosRequest($host,$user,$pass,$verify,$timeout,$path,$method='GET',?array $payload=null): array {
    $ch=curl_init('https://'.$host.'/rest'.$path);
    curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>strtoupper($method),CURLOPT_USERPWD=>$user.':'.$pass,CURLOPT_HTTPAUTH=>CURLAUTH_BASIC,CURLOPT_TIMEOUT=>$timeout,CURLOPT_CONNECTTIMEOUT=>$timeout,CURLOPT_HTTPHEADER=>['Content-Type: application/json']]);
    if(!$verify){curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);curl_setopt($ch,CURLOPT_SSL_VERIFYHOST,false);}
    if($payload!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_UNESCAPED_SLASHES));
    $response=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);
    if($response===false)throw new RuntimeException('cURL error: '.$err);
    $decoded=json_decode($response,true);
    if($code>=400)throw new RuntimeException('RouterOS HTTP '.$code.': '.(is_array($decoded)?json_encode($decoded,JSON_UNESCAPED_SLASHES):$response));
    return is_array($decoded)?$decoded:[];
}
function fetchConnections($h,$u,$p,$v,$t): array { return routerosRequest($h,$u,$p,$v,$t,'/ip/firewall/connection/print','POST',['.proplist'=>'.id,protocol,src-address,dst-address,src-port,dst-port,reply-src-address,reply-dst-address,reply-src-port,reply-dst-port,orig-bytes,repl-bytes,tcp-state,timeout,srcnat,dstnat']); }
function connectionKey(array $r): string { return (string)($r['.id']??implode('|',[$r['protocol']??'',$r['src-address']??'',$r['src-port']??'',$r['dst-address']??'',$r['dst-port']??''])); }
function isMulticastIpv4(string $ip): bool { if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_IPV4)===false)return false;$n=ip2long($ip);return $n!==false&&(($n & 0xF0000000)===0xE0000000); }
function describeHostConnection(array $r,string $ip): ?array {
    $src=(string)($r['src-address']??'');$dst=(string)($r['dst-address']??'');$replySrc=(string)($r['reply-src-address']??'');$replyDst=(string)($r['reply-dst-address']??'');
    if($src===$ip){$m=['direction'=>'outbound','remote_ip'=>$dst,'local_port'=>(string)($r['src-port']??''),'remote_port'=>(string)($r['dst-port']??''),'orig_is_upload'=>true];}
    elseif($dst===$ip){$m=['direction'=>'inbound','remote_ip'=>$src,'local_port'=>(string)($r['dst-port']??''),'remote_port'=>(string)($r['src-port']??''),'orig_is_upload'=>false];}
    elseif($replySrc===$ip){$m=['direction'=>'inbound','remote_ip'=>$replyDst,'local_port'=>(string)($r['reply-src-port']??''),'remote_port'=>(string)($r['reply-dst-port']??''),'orig_is_upload'=>false];}
    elseif($replyDst===$ip){$m=['direction'=>'inbound','remote_ip'=>$src,'local_port'=>(string)($r['reply-dst-port']??''),'remote_port'=>(string)($r['src-port']??''),'orig_is_upload'=>false];}
    else return null;
    if(isMulticastIpv4($m['remote_ip'])||$m['remote_ip']==='255.255.255.255')return null;
    return $m;
}
function sampleHost($h,$u,$p,$v,$t,$delay,string $ip): array {
    $a=fetchConnections($h,$u,$p,$v,$t);$start=microtime(true);usleep($delay);$b=fetchConnections($h,$u,$p,$v,$t);$seconds=max(microtime(true)-$start,.001);$first=[];foreach($a as $r)$first[connectionKey($r)]=$r;$rows=[];$downTotal=0.0;$upTotal=0.0;
    foreach($b as $r){$key=connectionKey($r);$meta=describeHostConnection($r,$ip);if($meta===null)continue;$origNow=(float)($r['orig-bytes']??0);$replNow=(float)($r['repl-bytes']??0);$origRate=0.0;$replRate=0.0;if(isset($first[$key])){$old=$first[$key];$origRate=max(0,$origNow-(float)($old['orig-bytes']??0))*8/$seconds;$replRate=max(0,$replNow-(float)($old['repl-bytes']??0))*8/$seconds;}$up=$meta['orig_is_upload']?$origRate:$replRate;$down=$meta['orig_is_upload']?$replRate:$origRate;$downTotal+=$down;$upTotal+=$up;$rows[]=['key'=>$key,'direction'=>$meta['direction'],'protocol'=>(string)($r['protocol']??''),'remote_ip'=>$meta['remote_ip'],'local_port'=>$meta['local_port'],'remote_port'=>$meta['remote_port'],'download_bps'=>$down,'upload_bps'=>$up,'download_text'=>formatBitsPerSecond($down),'upload_text'=>formatBitsPerSecond($up),'orig_bytes'=>$origNow,'repl_bytes'=>$replNow,'orig_is_upload'=>$meta['orig_is_upload']];}
    return ['ok'=>true,'refreshedAt'=>date('Y-m-d H:i:s'),'sampleSeconds'=>$seconds,'download_bps'=>$downTotal,'upload_bps'=>$upTotal,'download_text'=>formatBitsPerSecond($downTotal),'upload_text'=>formatBitsPerSecond($upTotal),'connections'=>$rows];
}
$ip=trim((string)($_GET['ip']??''));$iface=trim((string)($_GET['iface']??''));$ajax=($_GET['ajax']??'')==='1';$data=null;$error=null;
try{if(filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_IPV4)===false)throw new RuntimeException('Invalid or missing host IP.');$data=sampleHost($routerHost,$routerUser,$routerPass,$verifyTls,$timeoutSec,$sampleDelayUs,$ip);}catch(Throwable $e){$error=$e->getMessage();}
if($ajax){header('Content-Type: application/json; charset=utf-8',true,$error?500:200);echo json_encode($error?['ok'=>false,'error'=>$error]:$data,JSON_UNESCAPED_SLASHES);exit;}
$back=$iface!==''?'interface.php?iface='.rawurlencode($iface):'index.php';
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Host <?=h($ip)?> Traffic</title>
<style>
:root{--bg:#0f172a;--panel:#111827;--panel2:#1f2937;--text:#e5e7eb;--muted:#94a3b8;--line:#334155;--green:#22c55e;--red:#ef4444;--accent:#38bdf8}*{box-sizing:border-box}body{margin:0;font:14px Arial,sans-serif;background:var(--bg);color:var(--text)}.wrap{width:min(1700px,calc(100% - 32px));margin:24px auto}.topbar{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}.card{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:14px;padding:18px;margin-top:20px}h1,h2{margin:0}h2{font-size:18px}.muted{color:var(--muted)}.small{font-size:12px}.mono{font-family:Consolas,monospace}.stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.stat{border:1px solid #33415580;border-radius:10px;padding:12px}.label{color:var(--muted);font-size:12px}.value{font-size:18px;font-weight:700;margin-top:5px}.graph{width:100%;height:220px;background:#0f172a88;border:1px solid #33415580;border-radius:8px;margin-top:15px}.rx{color:#86efac}.tx{color:#fca5a5}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{padding:9px 10px;border-bottom:1px solid #33415580;text-align:left;white-space:nowrap}th{color:#cbd5e1;background:#ffffff08;position:sticky;top:0}.sortable{cursor:pointer;user-select:none}.sortable:hover{color:#fff}.sort-arrow{color:var(--accent);margin-left:4px}.filter{display:flex;align-items:center;gap:7px;cursor:pointer;user-select:none}.filter input{width:16px;height:16px}.error{background:#7f1d1d55;padding:15px;border-radius:10px}a{color:var(--accent)}@media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}}
</style></head><body><div class="wrap">
<div class="topbar"><div><h1>Host: <?=h($ip)?></h1><div class="muted small">Live traffic since this page was opened · <span id="when"></span></div></div><a href="<?=h($back)?>">Back to interface</a></div>
<?php if($error):?><div class="card error"><?=h($error)?></div><?php else:?>
<section class="card"><h2>Host Traffic</h2><div class="stats"><div class="stat"><div class="label">Download</div><div class="value rx" id="down">—</div></div><div class="stat"><div class="label">Upload</div><div class="value tx" id="up">—</div></div><div class="stat"><div class="label">Viewed Download</div><div class="value" id="downTotal">0 B</div></div><div class="stat"><div class="label">Viewed Upload</div><div class="value" id="upTotal">0 B</div></div><div class="stat"><div class="label">Connections Seen</div><div class="value" id="seenCount">0</div></div></div><canvas id="graph" class="graph" width="1600" height="220"></canvas><div class="muted small" style="margin-top:8px">Graph scale automatically follows the highest rate currently visible; the top line is the graph maximum. Totals use RouterOS conntrack counters across successive live polls; multicast/broadcast discovery traffic is hidden.</div></section>
<section class="card"><div class="topbar"><div><h2>Inbound Connections / History</h2><div class="muted small" style="margin-top:8px">Grouped by remote IP + local port. Remote/source ports are ignored.</div></div><label class="filter"><input type="checkbox" id="hideZero"> Hide 0 byte connections</label></div><div class="table-wrap" style="margin-top:14px"><table id="inboundTable"><thead><tr><th class="sortable" data-sort="protocol">Protocol</th><th class="sortable" data-sort="remote_ip">Remote IP</th><th class="sortable" data-sort="local_port">Local Port</th><th class="sortable" data-sort="connection_count">Connections</th><th class="sortable" data-sort="download_bps">Download</th><th class="sortable" data-sort="upload_bps">Upload</th><th class="sortable" data-sort="download_total">Viewed Download</th><th class="sortable" data-sort="upload_total">Viewed Upload</th></tr></thead><tbody id="inboundBody"></tbody></table></div></section>
<section class="card"><div class="topbar"><div><h2>Outbound Connections / History</h2><div class="muted small" style="margin-top:8px">Grouped by remote IP + remote port. Local/source ports are ignored.</div></div></div><div class="table-wrap" style="margin-top:14px"><table id="outboundTable"><thead><tr><th class="sortable" data-sort="protocol">Protocol</th><th class="sortable" data-sort="remote_ip">Remote IP</th><th class="sortable" data-sort="remote_port">Remote Port</th><th class="sortable" data-sort="connection_count">Connections</th><th class="sortable" data-sort="download_bps">Download</th><th class="sortable" data-sort="upload_bps">Upload</th><th class="sortable" data-sort="download_total">Viewed Download</th><th class="sortable" data-sort="upload_total">Viewed Upload</th></tr></thead><tbody id="outboundBody"></tbody></table></div></section>
<?php endif;?></div>
<script>
window.__initial=<?=json_encode($data,JSON_UNESCAPED_SLASHES)?>;
(function(){
const $=id=>document.getElementById(id),hist=[],rows=new Map(),counterBaselines=new Map(),maxPts=120;let downBytes=0,upBytes=0,polling=false;
const sorts={inbound:{key:localStorage.getItem('hostInboundSortKey')||'remote_ip',dir:localStorage.getItem('hostInboundSortDir')||'asc'},outbound:{key:localStorage.getItem('hostOutboundSortKey')||'remote_ip',dir:localStorage.getItem('hostOutboundSortDir')||'asc'}};
const hideZero=$('hideZero');if(hideZero){hideZero.checked=localStorage.getItem('hostHideZero')==='1';hideZero.addEventListener('change',()=>{localStorage.setItem('hostHideZero',hideZero.checked?'1':'0');renderTables()})}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function bytes(n){const u=['B','KB','MB','GB','TB'];let i=0;n=Math.max(0,n);while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]}
function bps(n){const u=['bps','Kbps','Mbps','Gbps','Tbps'];let i=0;n=Math.max(0,n);while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(i?2:0)+' '+u[i]}
function ipValue(v){return String(v||'').split('.').reduce((n,p)=>(n*256)+(Number(p)||0),0)}
function sortRows(list,s){return [...list].sort((a,b)=>{let av=a[s.key]??'',bv=b[s.key]??'';if(s.key==='remote_ip'){av=ipValue(av);bv=ipValue(bv)}else if(['local_port','remote_port','connection_count','download_bps','upload_bps','download_total','upload_total'].includes(s.key)){av=Number(av)||0;bv=Number(bv)||0}else{av=String(av).toLowerCase();bv=String(bv).toLowerCase()}let c=av<bv?-1:av>bv?1:0;if(!c)c=String(a.group_key||'').localeCompare(String(b.group_key||''));return s.dir==='asc'?c:-c})}
function updateHeaders(tableId,s){document.querySelectorAll('#'+tableId+' th.sortable').forEach(th=>{const base=th.dataset.label||th.textContent.replace(/[▲▼]\s*$/,'').trim();th.dataset.label=base;th.innerHTML=esc(base)+(th.dataset.sort===s.key?' <span class="sort-arrow">'+(s.dir==='asc'?'▲':'▼')+'</span>':'')})}
function bindSort(tableId,name){document.querySelectorAll('#'+tableId+' th.sortable').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.sort,s=sorts[name];if(s.key===key)s.dir=s.dir==='asc'?'desc':'asc';else{s.key=key;s.dir=['connection_count','download_bps','upload_bps','download_total','upload_total'].includes(key)?'desc':'asc'}localStorage.setItem('host'+(name==='inbound'?'Inbound':'Outbound')+'SortKey',s.key);localStorage.setItem('host'+(name==='inbound'?'Inbound':'Outbound')+'SortDir',s.dir);renderTables()}));updateHeaders(tableId,sorts[name])}
function draw(){const c=$('graph');if(!c||!hist.length)return;const x=c.getContext('2d'),w=c.width,h=c.height,left=74,right=10,top=10,bottom=20,plotW=w-left-right,plotH=h-top-bottom;x.clearRect(0,0,w,h);let m=1;hist.forEach(p=>m=Math.max(m,p.d,p.u));x.font='12px Arial';x.textAlign='right';x.textBaseline='middle';for(let i=0;i<=4;i++){const value=m*(4-i)/4,y=top+(plotH*i/4);x.strokeStyle='rgba(148,163,184,.18)';x.lineWidth=1;x.beginPath();x.moveTo(left,y);x.lineTo(w-right,y);x.stroke();x.fillStyle='#94a3b8';x.fillText(bps(value),left-8,y)}function line(k,col){x.beginPath();x.strokeStyle=col;x.lineWidth=2;hist.forEach((p,i)=>{const px=left+(i/Math.max(1,maxPts-1))*plotW,py=top+plotH-(p[k]/m)*plotH;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}line('d','#22c55e');line('u','#ef4444')}
function grouped(direction){const groups=new Map();for(const r of rows.values()){if(r.direction!==direction)continue;const gk=direction==='inbound'?[r.protocol,r.remote_ip,r.local_port].join('|'):[r.protocol,r.remote_ip,r.remote_port].join('|');let g=groups.get(gk);if(!g){g={group_key:gk,direction,protocol:r.protocol,remote_ip:r.remote_ip,local_port:r.local_port,remote_port:r.remote_port,connection_count:0,download_bps:0,upload_bps:0,download_total:0,upload_total:0};groups.set(gk,g)}g.connection_count++;g.download_bps+=Number(r.download_bps||0);g.upload_bps+=Number(r.upload_bps||0);g.download_total+=Number(r.download_total||0);g.upload_total+=Number(r.upload_total||0)}return [...groups.values()]}
function inboundHtml(r){return '<tr><td>'+esc(r.protocol)+'</td><td class="mono">'+esc(r.remote_ip)+'</td><td>'+esc(r.local_port||'—')+'</td><td>'+r.connection_count+'</td><td class="rx">'+bps(r.download_bps)+'</td><td class="tx">'+bps(r.upload_bps)+'</td><td>'+bytes(r.download_total)+'</td><td>'+bytes(r.upload_total)+'</td></tr>'}
function outboundHtml(r){return '<tr><td>'+esc(r.protocol)+'</td><td class="mono">'+esc(r.remote_ip)+'</td><td>'+esc(r.remote_port||'—')+'</td><td>'+r.connection_count+'</td><td class="rx">'+bps(r.download_bps)+'</td><td class="tx">'+bps(r.upload_bps)+'</td><td>'+bytes(r.download_total)+'</td><td>'+bytes(r.upload_total)+'</td></tr>'}
function renderTables(){let inbound=grouped('inbound'),outbound=grouped('outbound');if(hideZero&&hideZero.checked){const hasBytes=r=>r.download_total>0||r.upload_total>0;inbound=inbound.filter(hasBytes);outbound=outbound.filter(hasBytes)}inbound=sortRows(inbound,sorts.inbound);outbound=sortRows(outbound,sorts.outbound);$('inboundBody').innerHTML=inbound.map(inboundHtml).join('');$('outboundBody').innerHTML=outbound.map(outboundHtml).join('');updateHeaders('inboundTable',sorts.inbound);updateHeaders('outboundTable',sorts.outbound);$('seenCount').textContent=rows.size}
function render(d,initial=false){if(!d)return;$('when').textContent=d.refreshedAt||'';$('down').textContent=d.download_text||'—';$('up').textContent=d.upload_text||'—';let pollDown=0,pollUp=0;(d.connections||[]).forEach(r=>{const key=r.key,base=counterBaselines.get(key),orig=Number(r.orig_bytes||0),repl=Number(r.repl_bytes||0);let old=rows.get(key)||{...r,download_total:0,upload_total:0};if(base){const od=Math.max(0,orig-base.orig),rd=Math.max(0,repl-base.repl),up=r.orig_is_upload?od:rd,down=r.orig_is_upload?rd:od;old.download_total+=down;old.upload_total+=up;pollDown+=down;pollUp+=up}counterBaselines.set(key,{orig,repl});Object.assign(old,r);rows.set(key,old)});if(!initial){downBytes+=pollDown;upBytes+=pollUp}$('downTotal').textContent=bytes(downBytes);$('upTotal').textContent=bytes(upBytes);renderTables();hist.push({d:Number(d.download_bps||0),u:Number(d.upload_bps||0)});if(hist.length>maxPts)hist.shift();draw()}
async function poll(){if(polling)return;polling=true;try{const u=new URL(location.href);u.searchParams.set('ajax','1');u.searchParams.set('t',Date.now());const r=await fetch(u,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Update failed');render(d)}catch(e){console.error(e)}finally{polling=false}}
bindSort('inboundTable','inbound');bindSort('outboundTable','outbound');render(window.__initial,true);setInterval(poll,3000);
})();
</script></body></html>